### ISSUE TITLE
failure of installation

### ISSUE THREAD

**Issue by n1ce1995** [intel/xenomai-ethercat#1]
I build a linux kernel debian package and install it according to this website: [https://rtt-lwr.readthedocs.io/en/latest/rtpc/xenomai3.html](url) and then I try to compile your ethercat code，when I make kernel modules, I get something wrong:
make -C "/usr/src/linux-headers-4.9.146-xenomai-3.0.8" M="/home/sducnc/sourceCode/xenomai-ethercat-master" modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.146-xenomai-3.0.8'
make[3]: *** No rule to make target '/home/sducnc/sourceCode/xenomai-ethercat-master/devices/generic.o', needed by '/home/sducnc/sourceCode/xenomai-ethercat-master/devices/ec_generic.o'。 停止。
scripts/Makefile.build:555: recipe for target '/home/sducnc/sourceCode/xenomai-ethercat-master/devices' failed
make[2]: *** [/home/sducnc/sourceCode/xenomai-ethercat-master/devices] Error 2
Makefile:1530: recipe for target '_module_/home/sducnc/sourceCode/xenomai-ethercat-master' failed
make[1]: *** [_module_/home/sducnc/sourceCode/xenomai-ethercat-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.146-xenomai-3.0.8'
Makefile:934: recipe for target 'modules' failed
make: *** [modules] Error 2

Could you please give me some help? My email address is 180645471@qq.com

**Comment by intelzhangw2** [comment]
please use below configure command to build ethercat stack on xenomai:
1. bootstrap
2. configure --enable-sii-assign --disable-8139too --disable-eoe --enable-igb --libdir=/usr/xenomai/lib/ \
    --with-xenomai-dir=/usr/xenomai --with-xenomai-config=/usr/xenomai/bin/xeno-config \
    --with-linux-dir=<kernel output dir> --with-devices=8 --enable-rtdm \
    --enable-hrtimer --enable-cycles
3. make all modules

**Comment by n1ce1995** [comment]
According to your method, I compile your ethercat code again,but I get the same error information.
Linux kernel version is 4.9.146 and version of xenomai is 3.0.8.And I can lanuch the "latency" testsuite of xenomai. I guess if there is something wrong during my process of build the kernel package with xenoami patch?

**Comment by intelzhangw2** [comment]
Can you give me your all log for analysis?
Btw, have you confirmed if /usr/src/linux-headers-4.9.146-xenomai-3.0.8 is include your build objects?

**Comment by n1ce1995** [comment]
I'm sorry that I do not know the log you said so I copy my ethercat stack code after building to you（appendix）.
My compiling step is:
1. chmod +x bootstrap

2. ./bootstrap

3. ./configure --with-xenomai-dir=/usr/xenomai --with-xenomai-config=/usr/xenomai/bin/xeno-config --enable-sii-assign --disable-8139too --disable-eoe --enable-igb --libdir=/usr/xenomai/lib/ --prefix=/usr/local --with-linux-dir=/usr/src/linux-headers-4.9.146-xenomai-3.0.8 --with-devices=8 --enable-rtdm --enable-hrtimer --enable-cycles

make all modules

Error is as follow:
main.c: In function ‘main’:
main.c:274:24: warning: unused variable ‘param’ [-Wunused-variable]
     struct sched_param param = { .sched_priority = 82 };
                        ^
mv -f .deps/ec_xenomai_posix_example-main.Tpo .deps/ec_xenomai_posix_example-main.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -Wall -I../../include -I/usr/xenomai/include/cobalt -I/usr/xenomai/include -D_GNU_SOURCE -D_REENTRANT -fasynchronous-unwind-tables -D__COBALT__ -D__COBALT_WRAP__ -g -O2 -L../../lib/.libs -lethercat_rtdm -Wl,--no-as-needed -Wl,@/usr/xenomai/lib/cobalt.wrappers -Wl,@/usr/xenomai/lib/modechk.wrappers  /usr/xenomai/lib/xenomai/bootstrap.o -Wl,--wrap=main -Wl,--dynamic-list=/usr/xenomai/lib/dynlist.ld -L/usr/xenomai/lib -lcobalt -lmodechk -lpthread -lrt     -o ec_xenomai_posix_example ec_xenomai_posix_example-main.o 
libtool: link: gcc -Wall -I../../include -I/usr/xenomai/include/cobalt -I/usr/xenomai/include -D_GNU_SOURCE -D_REENTRANT -fasynchronous-unwind-tables -D__COBALT__ -D__COBALT_WRAP__ -g -O2 -Wl,--no-as-needed -Wl,@/usr/xenomai/lib/cobalt.wrappers -Wl,@/usr/xenomai/lib/modechk.wrappers /usr/xenomai/lib/xenomai/bootstrap.o -Wl,--wrap=main -Wl,--dynamic-list=/usr/xenomai/lib/dynlist.ld -o .libs/ec_xenomai_posix_example ec_xenomai_posix_example-main.o  -L../../lib/.libs /home/sducnc/sourceCode/xenomai-ethercat-master/lib/.libs/libethercat_rtdm.so -L/usr/xenomai/lib /usr/xenomai/lib/libcobalt.so /usr/xenomai/lib/libmodechk.so -lpthread -lrt
make[4]: Leaving directory '/home/sducnc/sourceCode/xenomai-ethercat-master/examples/xenomai_posix'
make[4]: Entering directory '/home/sducnc/sourceCode/xenomai-ethercat-master/examples'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/sducnc/sourceCode/xenomai-ethercat-master/examples'
make[3]: Leaving directory '/home/sducnc/sourceCode/xenomai-ethercat-master/examples'
make[2]: Leaving directory '/home/sducnc/sourceCode/xenomai-ethercat-master/examples'
make[2]: Entering directory '/home/sducnc/sourceCode/xenomai-ethercat-master'
make[2]: Leaving directory '/home/sducnc/sourceCode/xenomai-ethercat-master'
make[1]: Leaving directory '/home/sducnc/sourceCode/xenomai-ethercat-master'
make -C "/usr/src/linux-headers-4.9.146-xenomai-3.0.8" M="/home/sducnc/sourceCode/xenomai-ethercat-master" modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.146-xenomai-3.0.8'
make[3]: *** No rule to make target '/home/sducnc/sourceCode/xenomai-ethercat-master/devices/generic.o', needed by '/home/sducnc/sourceCode/xenomai-ethercat-master/devices/ec_generic.o'。 停止。
scripts/Makefile.build:555: recipe for target '/home/sducnc/sourceCode/xenomai-ethercat-master/devices' failed
make[2]: *** [/home/sducnc/sourceCode/xenomai-ethercat-master/devices] Error 2
Makefile:1530: recipe for target '_module_/home/sducnc/sourceCode/xenomai-ethercat-master' failed
make[1]: *** [_module_/home/sducnc/sourceCode/xenomai-ethercat-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.146-xenomai-3.0.8'
Makefile:934: recipe for target 'modules' failed
make: *** [modules] Error 2
[xenomai-ethercat-master.tar.gz](https://github.com/intel/xenomai-ethercat/files/3938114/xenomai-ethercat-master.tar.gz)

**Comment by intelzhangw2** [comment]
Before building etherstack, please confirm you have done to build kernel in /usr/src/linux-headers-4.9.146-xenomai-3.0.8 which is specified by “--with-linux-dir”.

**Comment by n1ce1995** [comment]
I built the linux kernel code and got two .deb packages and called make-kpkg command to install them.And then,I deleted the compiled linux kernel code.

**Comment by n1ce1995** [comment]
If you think my method is not suitable, give me a method of building and installing linux kernel,please?

**Comment by intelzhangw2** [comment]
As ethercat stack need to build kernel modules, you need to keep your linux compiled kernel code to build stack.
If you want to build ethercat deb, you can follow below step:

  1.  Bootstap
  2.  Modify ethercat.spec.in and add –with-linux-dir
  3.  configure --enable-sii-assign --disable-8139too --disable-eoe --enable-igb --libdir=/usr/xenomai/lib/ \

--with-xenomai-dir=/usr/xenomai --with-xenomai-config=/usr/xenomai/bin/xeno-config \

    --with-linux-dir=<linux dir> --with-devices=8 --enable-rtdm \
    --enable-hrtimer --enable-cycles
      4. rpmbuild --define "_builddir  <your ethercat path>" --target x86_64 -bb ethercat.spec

**Comment by n1ce1995** [comment]
I will try again. Thank you very much!

**Comment by intelzhangw2** [comment]
Please kindly let me know if your issue have fixed.

**Comment by n1ce1995** [comment]
Thank you for your help and attentions to my question. I'm sorry to say that I do not solve the problem.
According to your method, I compiled the linux kernel code under Ubuntu16.04.6 with gcc-5.4.The detailed step is:
1. make menuconfig
2. make
3. make modules_install install
And then, I boot the installed system with xenomai3 patches, and install xenomai3 user space library successfully.
Finally, I can compile the intel ethercat master stack successfully. But after installation, I find ethercat kernel module can not boot. I used to install and use IgH EtherCAT Master with Xenomai-2 many times and write some program to run servo motors. I know the servo will go to pre-op state if ethercat master boots normally, but at this time, when I execute "ethercat slaves" with a servo linked to the IPC, I get this error "Failed to obtain number of masters: Failed to open master device /dev/EtherCAT0: No such file or directory" .
I will appreciate it if you could give me a detailed instruction from building linux kernel. I mean no offense that I guess you are Chinese according to your nick name.If my guessing is right, could I communicate with you on WeChat,becausemy English is a little poor.

**Comment by intelzhangw2** [comment]
As you have done to compile stack, please parse your boot fail log  and /etc/sysconfig/ethercat?

**Comment by intelzhangw2** [comment]
as i know, you have fixed your issue.
let's close it
