### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by P1Epie** [intel/xenomai-ethercat#2]
I compiled the ethercat stack, but there were some errors.
$ sudo make modules
make -C "/usr/src/linux-headers-4.14.128-xenomai-3.0.8/" M="/home/8325b/Desktop/xenomai-ethercat-master" modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.128-xenomai-3.0.8'
  CC [M]  /home/8325b/Desktop/xenomai-ethercat-master/devices/generic.o
In file included from ./include/linux/compat.h:17:0,
                 from ./include/linux/ethtool.h:17,
                 from ./include/linux/netdevice.h:41,
                 from ./include/uapi/linux/if_arp.h:27,
                 from ./include/linux/if_arp.h:27,
                 from /home/8325b/Desktop/xenomai-ethercat-master/devices/generic.c:40:
./include/linux/if.h:28:54: fatal error: sys/socket.h: No such file or directory
compilation terminated.
scripts/Makefile.build:326: recipe for target '/home/8325b/Desktop/xenomai-ethercat-master/devices/generic.o' failed
make[3]: *** [/home/8325b/Desktop/xenomai-ethercat-master/devices/generic.o] Error 1
scripts/Makefile.build:585: recipe for target '/home/8325b/Desktop/xenomai-ethercat-master/devices' failed
make[2]: *** [/home/8325b/Desktop/xenomai-ethercat-master/devices] Error 2
Makefile:1534: recipe for target '_module_/home/8325b/Desktop/xenomai-ethercat-master' failed
make[1]: *** [_module_/home/8325b/Desktop/xenomai-ethercat-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.128-xenomai-3.0.8'
Makefile:934: recipe for target 'modules' failed
make: *** [modules] Error 2

My step:
1. chmod +x bootstrap
2. bootstrap
3. configure --enable-sii-assign --disable-8139too --disable-eoe --enable-igb --libdir=/usr/xenomai/lib/ --with-xenomai-dir=/usr/xenomai --with-xenomai-config=/usr/xenomai/bin/xeno-config  --with-linux-dir=/usr/src/linux-headers-4.14.128-xenomai-3.0.8 --with-devices=8 --enable-rtdm  --enable-hrtimer --enable-cycles
4. make all modules

Could you please give me some help?

**Comment by n1ce1995** [comment]
I met the same problem with you. Did you compile linux kernel to 2 debian packages and install them ? Try to compile linux kernel and install it dircetly and then compile and install this ethercat stack.

**Comment by P1Epie** [comment]
I installed the ethercat stack using the method in your conversations but problems are still there. Have you  installed it successfully?

**Comment by intelzhangw2** [comment]
@P1Epie do you need to use generic network driver? if no, please try to build it with --disable-generic

**Comment by P1Epie** [comment]
@intelzhangw2 According to your method, I built it with --disable-generic ,But igb has the same problem:
from /home/8325b/Desktop/xenomai-ethercat-master/devices/igb/igb_main-4.14-ethercat.c:32:
./include/linux/if.h:28:54: fatal error: sys/socket.h: No such file or directory

**Comment by intelzhangw2** [comment]
i have not found this issue.
it seem issue with "make kpkg". please refer to https://www.open-mesh.org/issues/333

**Comment by P1Epie** [comment]
Thanks for your help. I'll try again.

**Comment by intelzhangw2** [comment]
@P1Epie  Any upadte about this issue? if yes, let's to close it.

**Comment by P1Epie** [comment]
@intelzhangw2 Thank you
